import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext({
  lang: "en",
  setLang: () => {},
  t: (key) => key
});

const translations = {
  en: {
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.marketplace": "Marketplace",
    "nav.login": "Login",
    "nav.join": "Join SavvyFARM",
    "nav.logout": "Logout",
    "nav.lang": "Language",
    "brand.tag": "Contracts that feel fair",
    "footer.line": "Built for farmers and buyers. Transparent prices, confident decisions.",
    "hero.eyebrow": "SavvyFARM Contract Platform",
    "hero.title":
      "Farm-to-buyer contracts that respect the field, protect margins, and move with the season.",
    "hero.lede":
      "Create price-aware contracts, invite farmers to commit, and use AI pricing snapshots to keep every agreement transparent.",
    "hero.cta.buyer": "Start as a buyer",
    "hero.cta.farmer": "Join as a farmer",
    "hero.stat.ai": "market snapshots for every crop",
    "hero.stat.secure": "token-backed contract flow",
    "hero.stat.seasonal": "harvest windows modeled upfront",
    "hero.workflow.buyer": "Buyer workflow",
    "hero.workflow.farmer": "Farmer workflow",
    "hero.workflow.buyer.1": "Create a contract with AI price ranges",
    "hero.workflow.buyer.2": "Open it for farmer commitments",
    "hero.workflow.buyer.3": "Track filled quantity and lock dates",
    "hero.workflow.farmer.1": "Review open contracts and fair price bands",
    "hero.workflow.farmer.2": "Commit partial or full quantity",
    "hero.workflow.farmer.3": "Lock in harvest schedule with clarity",
    "feature.explain.title": "Price Explanation",
    "feature.explain.body":
      "Get a plain-language explanation alongside every AI snapshot, so farmers and buyers understand the why.",
    "feature.market.title": "Marketplace Pulse",
    "feature.market.body":
      "Browse active listings, place bids, and keep a record of every offer without guesswork.",
    "feature.location.title": "Location Smart",
    "feature.location.body":
      "Enable or relax location requirements depending on crop logistics.",
    "login.title": "Welcome back",
    "login.subtitle": "Log in to manage contracts, bids, and harvest schedules.",
    "login.button": "Login",
    "login.busy": "Signing in...",
    "login.footer": "New to SavvyFARM?",
    "login.footer.link": "Create an account",
    "register.title": "Join the SavvyFARM network",
    "register.subtitle": "Choose your role and start building confident crop agreements.",
    "register.button": "Create account",
    "register.busy": "Creating account...",
    "register.footer": "Already registered?",
    "register.footer.link": "Login",
    "buyer.eyebrow": "Buyer workspace",
    "buyer.title": "Welcome",
    "buyer.subtitle":
      "Draft contracts, open them for farmers, and use AI price explanation before you lock anything in.",
    "buyer.stats.total": "Total contracts",
    "buyer.stats.open": "Open for acceptance",
    "buyer.stats.locked": "Locked",
    "buyer.card.create": "Create a contract",
    "buyer.card.insight": "AI price insight",
    "buyer.card.contracts": "Your contracts",
    "buyer.button.preview": "Preview AI price",
    "buyer.button.explain": "Explain price",
    "buyer.button.explaining": "Explaining...",
    "buyer.button.create": "Create contract",
    "buyer.button.creating": "Creating...",
    "buyer.empty.title": "No contracts yet",
    "buyer.empty.body": "Create your first contract and open it for farmer commitments.",
    "buyer.empty.action": "Create now",
    "text.loadingContracts": "Loading contracts...",
    "text.previewHint": "Use \"Preview AI price\" to pull live pricing bands.",
    "text.loadingOpenContracts": "Loading open contracts...",
    "text.selectContract": "Select a contract from the list to commit.",
    "label.filledQty": "Filled quantity",
    "farmer.eyebrow": "Farmer workspace",
    "farmer.title": "Good day",
    "farmer.subtitle":
      "Browse open contracts, review fair price explanations, and commit only the quantity you can deliver.",
    "farmer.stats.open": "Open contracts",
    "farmer.stats.total": "Total available",
    "farmer.card.open": "Open contracts",
    "farmer.card.commit": "Commit to contract",
    "farmer.card.explain": "AI price explanation",
    "farmer.button.commit": "Commit crop",
    "farmer.button.view": "View contract",
    "farmer.button.explain": "Explain price",
    "farmer.button.explaining": "Explaining...",
    "farmer.empty.title": "No open contracts yet",
    "farmer.empty.body": "Buyers will post contracts soon. Check back later.",
    "market.eyebrow": "Marketplace",
    "market.title": "Live crop listings & competitive bids",
    "market.subtitle":
      "Buyers can bid on active listings, farmers can post fresh harvests with AI-backed base prices.",
    "market.post.title": "Post a listing",
    "market.button.snapshot": "AI snapshot",
    "market.button.create": "Create listing",
    "market.active": "Active listings",
    "market.closed": "Closed listings",
    "market.empty.active.title": "No active listings",
    "market.empty.active.body": "Farmers will add listings shortly.",
    "market.empty.closed.title": "No closed listings",
    "market.empty.closed.body": "When bidding closes or is cancelled, listings will appear here.",
    "market.bid.place": "Place bid",
    "contract.title": "Contract details",
    "contract.commitments": "Farmer commitments",
    "contract.loading": "Loading contract...",
    "label.crop": "Crop",
    "label.cropName": "Crop name",
    "label.state": "State",
    "label.variety": "Variety",
    "label.requiredQty": "Required quantity",
    "label.priceType": "Price type",
    "label.priceMin": "Offered min price",
    "label.priceMax": "Offered max price",
    "label.harvestStart": "Harvest start month",
    "label.harvestEnd": "Harvest end month",
    "label.harvestDate": "Harvest date (optional)",
    "label.locationRequired": "Require location match",
    "label.latitude": "Latitude",
    "label.longitude": "Longitude",
    "label.radius": "Radius (km)",
    "label.cluster": "Allow multiple farmers (cluster)",
    "label.commitQty": "Commit quantity",
    "label.quantity": "Quantity",
    "label.unit": "Unit",
    "label.basePrice": "Base price",
    "label.currentBid": "Current bid",
    "label.fairMin": "Fair min",
    "label.fairMax": "Fair max",
    "label.confidence": "Confidence",
    "label.explanation": "Explanation",
    "label.snapshot": "Snapshot",
    "label.fairRange": "Fair range",
    "option.range": "Range",
    "option.fixed": "Fixed",
    "option.select": "Select"
  },
  hi: {
    "nav.home": "होम",
    "nav.dashboard": "डैशबोर्ड",
    "nav.marketplace": "मार्केटप्लेस",
    "nav.login": "लॉगिन",
    "nav.join": "सैवीफार्म से जुड़ें",
    "nav.logout": "लॉगआउट",
    "nav.lang": "भाषा",
    "brand.tag": "न्यायसंगत समझौते",
    "footer.line": "किसानों और खरीदारों के लिए। पारदर्शी कीमतें, भरोसेमंद फैसले।",
    "hero.eyebrow": "SavvyFARM कॉन्ट्रैक्ट प्लेटफॉर्म",
    "hero.title":
      "खेत से खरीदार तक ऐसे कॉन्ट्रैक्ट जो मेहनत का सम्मान करें, मार्जिन बचाएं और मौसम के साथ चलें।",
    "hero.lede":
      "कीमत-जागरूक कॉन्ट्रैक्ट बनाएं, किसानों को कमिट करने के लिए आमंत्रित करें, और हर समझौते में पारदर्शिता रखें।",
    "hero.cta.buyer": "खरीदार के रूप में शुरू करें",
    "hero.cta.farmer": "किसान के रूप में जुड़ें",
    "hero.stat.ai": "हर फसल के लिए मार्केट स्नैपशॉट",
    "hero.stat.secure": "टोकन-समर्थित कॉन्ट्रैक्ट फ्लो",
    "hero.stat.seasonal": "पहले से तय कटाई विंडो",
    "hero.workflow.buyer": "खरीदार वर्कफ़्लो",
    "hero.workflow.farmer": "किसान वर्कफ़्लो",
    "hero.workflow.buyer.1": "AI रेंज के साथ कॉन्ट्रैक्ट बनाएं",
    "hero.workflow.buyer.2": "किसानों के लिए ओपन करें",
    "hero.workflow.buyer.3": "भरी हुई मात्रा और तारीखें ट्रैक करें",
    "hero.workflow.farmer.1": "ओपन कॉन्ट्रैक्ट और उचित कीमत रेंज देखें",
    "hero.workflow.farmer.2": "आंशिक या पूरी मात्रा कमिट करें",
    "hero.workflow.farmer.3": "स्पष्ट कटाई शेड्यूल तय करें",
    "feature.explain.title": "कीमत की व्याख्या",
    "feature.explain.body":
      "हर AI स्नैपशॉट के साथ सरल भाषा में वजह समझें — किसान और खरीदार दोनों के लिए।",
    "feature.market.title": "मार्केटप्लेस पल्स",
    "feature.market.body":
      "एक्टिव लिस्टिंग देखें, बोली लगाएं और हर ऑफर का रिकॉर्ड रखें।",
    "feature.location.title": "लोकेशन स्मार्ट",
    "feature.location.body":
      "फसल की लॉजिस्टिक्स के अनुसार लोकेशन की शर्तें तय करें।",
    "login.title": "वापसी पर स्वागत",
    "login.subtitle": "कॉन्ट्रैक्ट, बोलियां और कटाई शेड्यूल मैनेज करें।",
    "login.button": "लॉगिन",
    "login.busy": "लॉगिन हो रहा है...",
    "login.footer": "नई शुरुआत?",
    "login.footer.link": "खाता बनाएं",
    "register.title": "SavvyFARM नेटवर्क से जुड़ें",
    "register.subtitle": "अपना रोल चुनें और भरोसेमंद फसल समझौते शुरू करें।",
    "register.button": "खाता बनाएं",
    "register.busy": "खाता बन रहा है...",
    "register.footer": "पहले से पंजीकृत?",
    "register.footer.link": "लॉगिन",
    "buyer.eyebrow": "खरीदार वर्कस्पेस",
    "buyer.title": "स्वागत है",
    "buyer.subtitle":
      "कॉन्ट्रैक्ट ड्राफ्ट करें, किसानों के लिए ओपन करें, और लॉक करने से पहले AI व्याख्या देखें।",
    "buyer.stats.total": "कुल कॉन्ट्रैक्ट",
    "buyer.stats.open": "स्वीकृति के लिए ओपन",
    "buyer.stats.locked": "लॉक्ड",
    "buyer.card.create": "कॉन्ट्रैक्ट बनाएं",
    "buyer.card.insight": "AI कीमत इनसाइट",
    "buyer.card.contracts": "आपके कॉन्ट्रैक्ट",
    "buyer.button.preview": "AI कीमत देखें",
    "buyer.button.explain": "कीमत समझाएं",
    "buyer.button.explaining": "समझाया जा रहा है...",
    "buyer.button.create": "कॉन्ट्रैक्ट बनाएं",
    "buyer.button.creating": "बन रहा है...",
    "buyer.empty.title": "अभी कोई कॉन्ट्रैक्ट नहीं",
    "buyer.empty.body": "पहला कॉन्ट्रैक्ट बनाएं और किसानों के लिए ओपन करें।",
    "buyer.empty.action": "अभी बनाएं",
    "text.loadingContracts": "कॉन्ट्रैक्ट लोड हो रहे हैं...",
    "text.previewHint": "AI कीमत देखने के लिए \"AI कीमत देखें\" पर क्लिक करें।",
    "text.loadingOpenContracts": "ओपन कॉन्ट्रैक्ट लोड हो रहे हैं...",
    "text.selectContract": "कमिट करने के लिए सूची से कॉन्ट्रैक्ट चुनें।",
    "label.filledQty": "भरी हुई मात्रा",
    "farmer.eyebrow": "किसान वर्कस्पेस",
    "farmer.title": "नमस्ते",
    "farmer.subtitle":
      "ओपन कॉन्ट्रैक्ट देखें, उचित कीमत की व्याख्या समझें, और जितनी डिलीवर कर सकते हैं उतनी ही कमिट करें।",
    "farmer.stats.open": "ओपन कॉन्ट्रैक्ट",
    "farmer.stats.total": "कुल उपलब्ध",
    "farmer.card.open": "ओपन कॉन्ट्रैक्ट",
    "farmer.card.commit": "कॉन्ट्रैक्ट में कमिट करें",
    "farmer.card.explain": "AI कीमत की व्याख्या",
    "farmer.button.commit": "फसल कमिट करें",
    "farmer.button.view": "कॉन्ट्रैक्ट देखें",
    "farmer.button.explain": "कीमत समझाएं",
    "farmer.button.explaining": "समझाया जा रहा है...",
    "farmer.empty.title": "अभी कोई ओपन कॉन्ट्रैक्ट नहीं",
    "farmer.empty.body": "जल्द ही खरीदार कॉन्ट्रैक्ट पोस्ट करेंगे।",
    "market.eyebrow": "मार्केटप्लेस",
    "market.title": "लाइव लिस्टिंग और प्रतिस्पर्धी बोलियां",
    "market.subtitle":
      "खरीदार बोली लगाते हैं, किसान AI-समर्थित बेस कीमत के साथ लिस्टिंग पोस्ट करते हैं।",
    "market.post.title": "लिस्टिंग पोस्ट करें",
    "market.button.snapshot": "AI स्नैपशॉट",
    "market.button.create": "लिस्टिंग बनाएं",
    "market.active": "एक्टिव लिस्टिंग",
    "market.closed": "बंद लिस्टिंग",
    "market.empty.active.title": "कोई एक्टिव लिस्टिंग नहीं",
    "market.empty.active.body": "किसान जल्द ही लिस्टिंग जोड़ेंगे।",
    "market.empty.closed.title": "कोई बंद लिस्टिंग नहीं",
    "market.empty.closed.body": "बोली बंद होने पर लिस्टिंग यहां दिखेंगी।",
    "market.bid.place": "बोली लगाएं",
    "contract.title": "कॉन्ट्रैक्ट विवरण",
    "contract.commitments": "किसान कमिटमेंट्स",
    "contract.loading": "कॉन्ट्रैक्ट लोड हो रहा है...",
    "label.crop": "फसल",
    "label.cropName": "फसल का नाम",
    "label.state": "राज्य",
    "label.variety": "वैरायटी",
    "label.requiredQty": "जरूरी मात्रा",
    "label.priceType": "कीमत प्रकार",
    "label.priceMin": "न्यूनतम ऑफर कीमत",
    "label.priceMax": "अधिकतम ऑफर कीमत",
    "label.harvestStart": "कटाई शुरू महीना",
    "label.harvestEnd": "कटाई अंत महीना",
    "label.harvestDate": "कटाई तारीख (वैकल्पिक)",
    "label.locationRequired": "लोकेशन मैच आवश्यक",
    "label.latitude": "अक्षांश",
    "label.longitude": "देशांतर",
    "label.radius": "रेडियस (किमी)",
    "label.cluster": "एक से अधिक किसान अनुमति (क्लस्टर)",
    "label.commitQty": "कमिट मात्रा",
    "label.quantity": "मात्रा",
    "label.unit": "यूनिट",
    "label.basePrice": "बेस कीमत",
    "label.currentBid": "वर्तमान बोली",
    "label.fairMin": "न्यायसंगत न्यूनतम",
    "label.fairMax": "न्यायसंगत अधिकतम",
    "label.confidence": "विश्वास स्तर",
    "label.explanation": "व्याख्या",
    "label.snapshot": "स्नैपशॉट",
    "label.fairRange": "न्यायसंगत रेंज",
    "option.range": "रेंज",
    "option.fixed": "फिक्स्ड",
    "option.select": "चुनें"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = window.localStorage.getItem("sf_lang");
    return stored || "en";
  });

  const value = useMemo(() => {
    function t(key) {
      return translations[lang]?.[key] || translations.en[key] || key;
    }

    function updateLang(next) {
      setLang(next);
      window.localStorage.setItem("sf_lang", next);
    }

    return { lang, setLang: updateLang, t };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
